import type { CatalogAsset, CatalogCategory } from "./types";

/**
 * Isolated mock catalog for storefront visuals until PostgreSQL catalog
 * queries are wired. Replace `catalog.ts` consumers with repository reads.
 * Every image URL here stands in for a THUMBNAIL or WATERMARKED_PREVIEW
 * `publicUrl`. Do not treat these as masters or working previews.
 */
const unsplash = (id: string, width: number) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${String(width)}&q=75`;

export const mockCategories: CatalogCategory[] = [
  {
    id: "cat_gods",
    name: "Gods & Deities",
    slug: "gods-and-deities",
    description: "Devotional and sculptural imagery of Hindu deities.",
    parentId: null,
  },
  {
    id: "cat_ganesha",
    name: "Ganesha",
    slug: "ganesha",
    description: "Ganesha sculpture, painting, and festival scenes.",
    parentId: "cat_gods",
  },
  {
    id: "cat_krishna",
    name: "Krishna",
    slug: "krishna",
    description: "Krishna, Radha, and flute-playing murti imagery.",
    parentId: "cat_gods",
  },
  {
    id: "cat_shiva",
    name: "Shiva",
    slug: "shiva",
    description: "Shiva sculpture, trident, and temple-side murti.",
    parentId: "cat_gods",
  },
  {
    id: "cat_vishnu",
    name: "Vishnu & Venkateswara",
    slug: "vishnu-and-venkateswara",
    description: "Vishnu, Venkateswara, and related Vaishnava forms.",
    parentId: "cat_gods",
  },
  {
    id: "cat_durga",
    name: "Durga",
    slug: "durga",
    description: "Durga Puja and Navratri goddess imagery.",
    parentId: "cat_gods",
  },
  {
    id: "cat_lakshmi",
    name: "Lakshmi",
    slug: "lakshmi",
    description: "Lakshmi and prosperity-goddess idol portraits.",
    parentId: "cat_gods",
  },
  {
    id: "cat_hanuman",
    name: "Hanuman",
    slug: "hanuman",
    description: "Hanuman murti, blessing pose, and temple sculpture.",
    parentId: "cat_gods",
  },
  {
    id: "cat_murugan",
    name: "Murugan",
    slug: "murugan",
    description: "Murugan, Kartikeya, and vel-bearing shrine imagery.",
    parentId: "cat_gods",
  },
  {
    id: "cat_festivals",
    name: "Festivals",
    slug: "festivals",
    description: "Diwali, Holi, and seasonal celebration imagery.",
    parentId: null,
  },
  {
    id: "cat_diwali",
    name: "Diwali",
    slug: "diwali",
    description: "Lamps, rangoli, and night-time festival light.",
    parentId: "cat_festivals",
  },
  {
    id: "cat_art",
    name: "Traditional Art",
    slug: "traditional-art",
    description: "Indian painting, textile, and decorative arts.",
    parentId: null,
  },
  {
    id: "cat_architecture",
    name: "Architecture",
    slug: "architecture",
    description: "Temples, palaces, and carved stone detail.",
    parentId: null,
  },
  {
    id: "cat_nature",
    name: "Nature & Landscapes",
    slug: "nature-and-landscapes",
    description: "Indian landscapes, flora, and wildlife.",
    parentId: null,
  },
  {
    id: "cat_backgrounds",
    name: "Patterns & Backgrounds",
    slug: "patterns-and-backgrounds",
    description: "Textures, motifs, and printable backgrounds.",
    parentId: null,
  },
];

const rawAssets: Omit<CatalogAsset, "licenses">[] = [
  {
    id: "asset_01",
    code: "BS-20260815-000001",
    title: "Ornate Ganesha in Sanctum Light",
    slug: "ornate-ganesha-in-sanctum-light",
    description:
      "Close portrait of a jeweled Ganesha murti with a golden crown.",
    categoryId: "cat_ganesha",
    categoryName: "Ganesha",
    categorySlug: "ganesha",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["ganesha", "devotional", "idol", "hindu"],
    thumbnailPublicUrl: unsplash("photo-1567591370504-80142b28f1c1", 800),
    previewPublicUrl: unsplash("photo-1567591370504-80142b28f1c1", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 249900,
    publishedAt: "2026-08-15T09:00:00.000Z",
  },
  {
    id: "asset_02",
    code: "BS-20260815-000002",
    title: "Goddess Durga on a Golden Throne",
    slug: "goddess-durga-on-a-golden-throne",
    description:
      "Navratri Durga idol seated with trident, lamps, and floral shrine.",
    categoryId: "cat_durga",
    categoryName: "Durga",
    categorySlug: "durga",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["durga", "navratri", "goddess", "devotional"],
    thumbnailPublicUrl: unsplash("photo-1761471678522-79012da5bd71", 800),
    previewPublicUrl: unsplash("photo-1761471678522-79012da5bd71", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 219900,
    publishedAt: "2026-08-14T16:00:00.000Z",
  },
  {
    id: "asset_03",
    code: "BS-20260814-000003",
    title: "Hanuman Blessing Against Blue Sky",
    slug: "hanuman-blessing-against-blue-sky",
    description:
      "Saffron Hanuman murti with abhaya mudra and a golden crown.",
    categoryId: "cat_hanuman",
    categoryName: "Hanuman",
    categorySlug: "hanuman",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["hanuman", "bajrangbali", "devotional", "statue"],
    thumbnailPublicUrl: unsplash("photo-1780633208189-ec53c80fb111", 800),
    previewPublicUrl: unsplash("photo-1780633208189-ec53c80fb111", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 199900,
    publishedAt: "2026-08-14T11:30:00.000Z",
  },
  {
    id: "asset_04",
    code: "BS-20260814-000004",
    title: "Murudeshwar Shiva Over the Sea",
    slug: "murudeshwar-shiva-over-the-sea",
    description:
      "Monumental seated Shiva with trident and damaru on the Karnataka coast.",
    categoryId: "cat_shiva",
    categoryName: "Shiva",
    categorySlug: "shiva",
    width: 6000,
    height: 4000,
    format: "JPEG",
    orientation: "LANDSCAPE",
    tags: ["shiva", "mahadev", "sculpture", "temple"],
    thumbnailPublicUrl: unsplash("photo-1566890910598-c5768889e83e", 800),
    previewPublicUrl: unsplash("photo-1566890910598-c5768889e83e", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 269900,
    publishedAt: "2026-08-14T08:00:00.000Z",
  },
  {
    id: "asset_05",
    code: "BS-20260813-000005",
    title: "Krishna Playing Flute for Devotees",
    slug: "krishna-playing-flute-for-devotees",
    description:
      "Miniature painting of blue-skinned Krishna with flute, gopis, and cow.",
    categoryId: "cat_art",
    categoryName: "Traditional Art",
    categorySlug: "traditional-art",
    width: 3600,
    height: 5400,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["krishna", "painting", "traditional-art", "bansuri"],
    thumbnailPublicUrl: unsplash("photo-1719498482293-7ed698f58739", 800),
    previewPublicUrl: unsplash("photo-1719498482293-7ed698f58739", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 189900,
    publishedAt: "2026-08-13T16:20:00.000Z",
  },
  {
    id: "asset_06",
    code: "BS-20260813-000006",
    title: "Four-Armed Vishnu with Chakra and Conch",
    slug: "four-armed-vishnu-with-chakra-and-conch",
    description:
      "Vishnu murti with sudarshana chakra and shankha, a Venkateswara form.",
    categoryId: "cat_vishnu",
    categoryName: "Vishnu & Venkateswara",
    categorySlug: "vishnu-and-venkateswara",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["vishnu", "venkateswara", "balaji", "deity"],
    thumbnailPublicUrl: unsplash("photo-1558877398-d71724903422", 800),
    previewPublicUrl: unsplash("photo-1558877398-d71724903422", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 229900,
    publishedAt: "2026-08-13T10:00:00.000Z",
  },
  {
    id: "asset_07",
    code: "BS-20260812-000007",
    title: "Radha and Krishna in Festival Flowers",
    slug: "radha-and-krishna-in-festival-flowers",
    description:
      "Temple shrine of Radha-Krishna dressed in silk among lotus garlands.",
    categoryId: "cat_krishna",
    categoryName: "Krishna",
    categorySlug: "krishna",
    width: 6000,
    height: 4000,
    format: "JPEG",
    orientation: "LANDSCAPE",
    tags: ["krishna", "radha", "festival", "devotional"],
    thumbnailPublicUrl: unsplash("photo-1747548175213-91b549c07392", 800),
    previewPublicUrl: unsplash("photo-1747548175213-91b549c07392", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 179900,
    publishedAt: "2026-08-12T14:10:00.000Z",
  },
  {
    id: "asset_08",
    code: "BS-20260812-000008",
    title: "Lakshmi Adorned with Marigold Garlands",
    slug: "lakshmi-adorned-with-marigold-garlands",
    description:
      "Goddess portrait with golden crown, pearls, and Diwali marigolds.",
    categoryId: "cat_lakshmi",
    categoryName: "Lakshmi",
    categorySlug: "lakshmi",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["lakshmi", "goddess", "diwali", "devotional"],
    thumbnailPublicUrl: unsplash("photo-1602772576751-f90059b6a8ff", 800),
    previewPublicUrl: unsplash("photo-1602772576751-f90059b6a8ff", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 209900,
    publishedAt: "2026-08-12T09:40:00.000Z",
  },
  {
    id: "asset_09",
    code: "BS-20260811-000009",
    title: "Murugan with Vel at the Cave Shrine",
    slug: "murugan-with-vel-at-the-cave-shrine",
    description:
      "Kartikeya holding the vel beside a peacock under a ceremonial chatra.",
    categoryId: "cat_murugan",
    categoryName: "Murugan",
    categorySlug: "murugan",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["murugan", "kartikeya", "vel", "temple"],
    thumbnailPublicUrl: unsplash("photo-1570530805197-2a37d9e84332", 800),
    previewPublicUrl: unsplash("photo-1570530805197-2a37d9e84332", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 169900,
    publishedAt: "2026-08-11T18:00:00.000Z",
  },
  {
    id: "asset_10",
    code: "BS-20260811-000010",
    title: "Bronze Krishna with Flute Shadow",
    slug: "bronze-krishna-with-flute-shadow",
    description:
      "Polished bronze Krishna in tribhanga pose playing the bansuri.",
    categoryId: "cat_krishna",
    categoryName: "Krishna",
    categorySlug: "krishna",
    width: 4000,
    height: 4000,
    format: "JPEG",
    orientation: "SQUARE",
    tags: ["krishna", "bronze", "flute", "sculpture"],
    thumbnailPublicUrl: unsplash("photo-1641730259879-ad98e7db7bcb", 800),
    previewPublicUrl: unsplash("photo-1641730259879-ad98e7db7bcb", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 159900,
    publishedAt: "2026-08-11T12:15:00.000Z",
  },
  {
    id: "asset_11",
    code: "BS-20260810-000011",
    title: "South Indian Gopuram with Temple Deities",
    slug: "south-indian-gopuram-with-temple-deities",
    description:
      "Painted Dravidian temple tower with Murugan, peacock, and goddesses.",
    categoryId: "cat_architecture",
    categoryName: "Architecture",
    categorySlug: "architecture",
    width: 6000,
    height: 4000,
    format: "JPEG",
    orientation: "LANDSCAPE",
    tags: ["temple", "gopuram", "murugan", "deity"],
    thumbnailPublicUrl: unsplash("photo-1658658160517-c9b44dbbdb0b", 800),
    previewPublicUrl: unsplash("photo-1658658160517-c9b44dbbdb0b", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 239900,
    publishedAt: "2026-08-10T07:45:00.000Z",
  },
  {
    id: "asset_12",
    code: "BS-20260810-000012",
    title: "Marble Radha and Krishna Murtis",
    slug: "marble-radha-and-krishna-murtis",
    description:
      "White marble Radha-Krishna pair with gold crowns and flower malas.",
    categoryId: "cat_krishna",
    categoryName: "Krishna",
    categorySlug: "krishna",
    width: 5000,
    height: 5000,
    format: "JPEG",
    orientation: "SQUARE",
    tags: ["krishna", "radha", "marble", "murti"],
    thumbnailPublicUrl: unsplash("photo-1590228947699-5f1fa1d86458", 800),
    previewPublicUrl: unsplash("photo-1590228947699-5f1fa1d86458", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 149900,
    publishedAt: "2026-08-10T05:30:00.000Z",
  },
  {
    id: "asset_13",
    code: "BS-20260809-000013",
    title: "Garden Ganesha with Marigold Garland",
    slug: "garden-ganesha-with-marigold-garland",
    description:
      "Stone Ganesha in blessing mudra, draped with yellow marigolds.",
    categoryId: "cat_ganesha",
    categoryName: "Ganesha",
    categorySlug: "ganesha",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["ganesha", "marigold", "garden", "devotional"],
    thumbnailPublicUrl: unsplash("photo-1539014861783-7ac37e9d290c", 800),
    previewPublicUrl: unsplash("photo-1539014861783-7ac37e9d290c", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 129900,
    publishedAt: "2026-08-09T13:00:00.000Z",
  },
  {
    id: "asset_14",
    code: "BS-20260809-000014",
    title: "Meditative Shiva with Trident",
    slug: "meditative-shiva-with-trident",
    description:
      "Seated Shiva murti with cobra, crescent moon, and om on the palm.",
    categoryId: "cat_shiva",
    categoryName: "Shiva",
    categorySlug: "shiva",
    width: 4000,
    height: 6000,
    format: "TIFF",
    orientation: "PORTRAIT",
    tags: ["shiva", "trident", "meditation", "sculpture"],
    thumbnailPublicUrl: unsplash("photo-1740910924105-13247b79c0a9", 800),
    previewPublicUrl: unsplash("photo-1740910924105-13247b79c0a9", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 199900,
    publishedAt: "2026-08-09T09:00:00.000Z",
  },
  {
    id: "asset_15",
    code: "BS-20260808-000015",
    title: "Temple Tower with Rama and Ganesha",
    slug: "temple-tower-with-rama-and-ganesha",
    description:
      "South Indian gopuram sculptures including Rama with bow and Ganesha.",
    categoryId: "cat_gods",
    categoryName: "Gods & Deities",
    categorySlug: "gods-and-deities",
    width: 6000,
    height: 4000,
    format: "JPEG",
    orientation: "LANDSCAPE",
    tags: ["rama", "ganesha", "temple", "gopuram"],
    thumbnailPublicUrl: unsplash("photo-1527221579996-0de6d1ae2069", 800),
    previewPublicUrl: unsplash("photo-1527221579996-0de6d1ae2069", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 189900,
    publishedAt: "2026-08-08T15:00:00.000Z",
  },
  {
    id: "asset_16",
    code: "BS-20260808-000016",
    title: "Festival Ganesha in Silk and Jewels",
    slug: "festival-ganesha-in-silk-and-jewels",
    description:
      "Seated Ganesha murti in festival dress, suited to Diwali puja art.",
    categoryId: "cat_diwali",
    categoryName: "Diwali",
    categorySlug: "diwali",
    width: 4000,
    height: 6000,
    format: "JPEG",
    orientation: "PORTRAIT",
    tags: ["diwali", "ganesha", "lakshmi", "festival"],
    thumbnailPublicUrl: unsplash("photo-1607604760190-ec9ccc12156e", 800),
    previewPublicUrl: unsplash("photo-1607604760190-ec9ccc12156e", 1600),
    defaultLicenseName: "Standard",
    pricePaise: 119900,
    publishedAt: "2026-08-08T08:00:00.000Z",
  },
];

export const mockAssets: CatalogAsset[] = rawAssets.map((asset) => ({
  ...asset,
  licenses: [
    {
      id: `${asset.id}-standard`,
      code: "STANDARD",
      name: "Standard",
      pricePaise: asset.pricePaise,
      isDefault: true,
    },
  ],
}));
